require('dotenv').config();
const express = require('express');
const morgan = require('morgan');
const cors = require('cors');
const connectDB = require('./src/config/db');

const leadsRoute = require('./src/routes/leadRoutes');
const { errorHandler, notFound } = require('./src/middleware/errorHandler');
const app = express();
connectDB();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
if (process.env.NODE_ENV !== 'production') app.use(morgan('dev'));
app.use('/api/leads', leadsRoute);
app.get('/', (req, res) => res.json({ ok: true, message: 'Lead Management API' }));
app.use(notFound);
app.use(errorHandler);
const PORT = process.env.PORT || 5004;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));